#!/bin/bash
set -e

# Runs both server and one site

export PYTHONPATH=`pwd`/../../../src:$PYTHONPATH

python ../../../examples/octopus/run_site.py --config site.yaml &
SPID=`jobs -p 1`
echo "Site PID is $SPID"

cleanup() {
    echo Killing $SPID; pkill -e -P $SPID; kill $SPID
}

trap cleanup SIGINT

sleep 10

python ../../../examples/octopus/run_server.py --config server.yaml


cleanup